create type public.app_role as enum ('admin','graphic');
create type public.job_state as enum ('pending','accepted');
create type public.workflow_state as enum ('ยังไม่ดำเนินการ','กำลังดำเนินการ','ติดตามผล','เสร็จแล้ว','ยกเลิก');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role public.app_role not null default 'graphic',
  active boolean not null default true,
  can_accept_jobs boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.jobs (
  id bigint generated by default as identity primary key,
  document_no text not null unique,
  requester text not null,
  department text not null,
  priority text not null,
  start_date date not null,
  due_from date not null,
  due_to date not null,
  purpose text,
  total_qty integer not null check (total_qty > 0),
  delivery_channel text not null check (delivery_channel in ('LINE','Email')),
  delivery_contact text not null,
  reference_link text,
  state public.job_state not null default 'pending',
  workflow_status public.workflow_state not null default 'ยังไม่ดำเนินการ',
  accepted_by uuid references auth.users(id) on delete set null,
  accepted_at timestamptz,
  delivery_link text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.job_items (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  position integer not null,
  type text not null,
  type_other text,
  title text not null,
  material text,
  copy_text text not null,
  width numeric(12,2) not null check (width >= 0),
  height numeric(12,2) not null check (height >= 0),
  unit text not null,
  print_required boolean not null,
  quantity integer not null check (quantity > 0),
  note text,
  reference_link text,
  unique(job_id, position)
);

create table public.request_files (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  storage_path text not null unique,
  file_name text not null,
  mime_type text,
  file_size bigint check (file_size is null or file_size <= 10485760),
  created_at timestamptz not null default now()
);

create table public.delivery_files (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  uploaded_by uuid references auth.users(id) on delete set null,
  storage_path text not null unique,
  file_name text not null,
  mime_type text,
  file_size bigint,
  created_at timestamptz not null default now()
);

create index jobs_created_at_idx on public.jobs(created_at desc);
create index jobs_state_created_at_idx on public.jobs(state, created_at desc);
create index jobs_workflow_status_idx on public.jobs(workflow_status);
create index job_items_job_id_idx on public.job_items(job_id);
create index request_files_job_id_idx on public.request_files(job_id);
create index delivery_files_job_id_idx on public.delivery_files(job_id);

alter table public.profiles enable row level security;
alter table public.jobs enable row level security;
alter table public.job_items enable row level security;
alter table public.request_files enable row level security;
alter table public.delivery_files enable row level security;

create policy "users read own profile" on public.profiles for select to authenticated
using ((select auth.uid()) = id);
create policy "staff read jobs" on public.jobs for select to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.active));
create policy "staff update jobs" on public.jobs for update to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.active))
with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.active));
create policy "staff read job items" on public.job_items for select to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.active));
create policy "staff read request files" on public.request_files for select to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.active));
create policy "staff read delivery files" on public.delivery_files for select to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.active));
create policy "staff insert delivery files" on public.delivery_files for insert to authenticated
with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.active));

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values
('request-files','request-files',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf']),
('delivery-files','delivery-files',false,52428800,null)
on conflict (id) do nothing;
